### ISSUE TITLE
no-confusing-arrow & arrow-body-style conflict with Prettier

### ISSUE THREAD

**Issue by kgrhartlage** [labforward/labforward-config-base#4]
Our current use of both [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style) and [no-confusing-arrow](https://eslint.org/docs/rules/no-confusing-arrow) conflicts with `Prettier`

This results in an `no-confusing-arrow` error:

```javascript
const MyComponent = (props) => condition ? <Foo /> : <Bar />
```

The `allowParens` option (`true` by default) allows this syntax:

```javascript
const MyComponent = (props) => (condition ? <Foo /> : <Bar />)
```

`Prettier`, however, will remove those parentheses again.

We also cannot add an explicit `return`, because that results in an `arrow-body-style` error:

```javascript
const MyComponent = (props) => {
  return condition ? <Foo /> : <Bar />
}
```

To solve this, we could enforce braces around the function body. IIUC object literals would not be affected. Personally, I would much prefer disabling or removing `no-confusing-arrow`.

**Comment by ignatiusreza** [comment]
Could you check how it behaves with `allowParens: false`?

ref: https://nicedoc.io/prettier/eslint-config-prettier#no-confusing-arrow

**Comment by kgrhartlage** [comment]
> allowParens: false

same thing, stuck in a cycle of one or the other rule complaining.

**Comment by ignatiusreza** [comment]
okay, let's remove `no-confusing-arrow` then..

**Comment by doktordirk** [comment]
alright. though ideally i'd like to use `const MyComponent = (props) => (condition ? <Foo /> : <Bar />)` style for ternaries

**Comment by kgrhartlage** [comment]
IIUC there is no `Prettier` option to configure that. There is only only one for the parameter parentheses, but not for the body

**Comment by doktordirk** [comment]
that's what i dislike about prettier. it has one or two annoying styles. but it's still better than without prettier

**Comment by ignatiusreza** [comment]
with auto formatter, there bound to be one or two things which doesn't feel right to some people.. there're anyway no universal truth as to which style are better.. but, having auto formatter is still better then not having one.. :shrug:
